stages:
  - merge

auto-merge-docs-to-main:
  stage: merge
  script:
    - git checkout main
    - git pull --no-rebase
    - git checkout backend docs
    - git add docs
    - git diff --staged --quiet || git commit -m "Merged /docs from $CI_COMMIT_BRANCH"
    - git remote set-url origin https://oauth2:${ProjectAccessToken}@gitalcoi.dsic.upv.es/hmongom_upv/eshop
    - git push origin main
  only:
    changes:
      - docs/**/*
  except:
    - main
    - release