stages:
  - merge

auto-merge-docs-to-main:
  stage: merge
  script:
    - git checkout main
    - git fetch
    - git checkout $CI_COMMIT_BRANCH docs
    - git add docs
    - git commit -m "Merged /docs from $CI_COMMIT_BRANCH"
    - git push
  only:
    changes:
      - docs/**/*
  except:
    - main
    - release