stages:
  - merge

auto-merge-docs-to-main:
  stage: merge
  script: |
      git fetch origin main
      git checkout main

      # Add all changes in docs/ to the staging area
      git add docs/

      # Commit the changes
      git commit -m "Merged changes from docs/ of $CI_COMMIT_BRANCH into main"

      # Push the changes to the main branch
      git push https://hmongom_upv:${ProjectAccessToken}@gitalcoi.dsic.upv.es/hmongom_upv/eshop main

  only:
    changes:
      - docs/**/*
      - documentation/**/*
  except:
    - main
    - release
