on:
  push:
    branches:
      - '*'

stages:
  - merge

auto-merge-docs-to-main:
  stage: merge
  script:
    - git checkout origin/main
    - git fetch
    - git add -A
    - git stash
    - git checkout origin/$CI_COMMIT_BRANCH docs
    - git add docs
    - git commit -m "Merged /docs from $CI_COMMIT_BRANCH"
    - git push
  only:
    changes:
      - docs/**/*
      - documentation/**/*
